const darkOn = () => {
    var on = document.getElementById('darkmode_on');
    var off = document.getElementById('darkmode_off');
    on.style.display = 'block';
    off.style.display = 'none';
    var home = document.getElementById('home')
    home.style.backgroundImage = 'radial-gradient(black, black)'

    var nav = document.getElementById('nav');
    nav.style.backgroundColor = 'black';
    var mob_nav = document.getElementById('mob-nav');
    mob_nav.style.backgroundColor = 'black';
    var nav_btn_logo = document.getElementById('nav-btn-logo');
    nav_btn_logo.style.backgroundColor = 'white'
    nav_btn_logo.style.color = 'black'
    var nav_link_soc_1 = document.getElementById('nav_link_soc_1');
    var nav_link_soc_2 = document.getElementById('nav_link_soc_2');
    var nav_link_soc_3 = document.getElementById('nav_link_soc_3');
    var nav_link_soc_4 = document.getElementById('nav_link_soc_4');
    nav_link_soc_1.style.color = 'white'
    nav_link_soc_2.style.color = 'white'
    nav_link_soc_3.style.color = 'white'
    nav_link_soc_4.style.color = 'white'
    var page_links_1 = document.getElementById('page_links_1')
    page_links_1.style.color = 'grey'
    var page_links_2 = document.getElementById('page_links_2')
    page_links_2.style.color = 'grey'
    var page_links_3 = document.getElementById('page_links_3')
    page_links_3.style.color = 'grey'
    var page_links_4 = document.getElementById('page_links_4')
    page_links_4.style.color = 'grey'
    var first_sec = document.getElementById('first_sec');
    first_sec.style.color = 'white'
    var mca = document.getElementById('mca')
    var intro = document.getElementById('intro')
    var tagline = document.getElementById('tagline')
    mca.style.color = 'grey'
    intro.style.color = 'grey'
    tagline.style.color = 'white'
    var about = document.getElementById('about')
    about.style.backgroundColor = 'black'
    var about_h1 = document.getElementById('about_h1')
    about_h1.style.color = 'white'
    var main_about_h1 = document.getElementById('main_about_h1')
    main_about_h1.style.color = 'white'
    var p = document.getElementById('p')
    p.style.color = 'white'
    var p_intro = document.getElementById('p_intro')
    p_intro.style.color = 'white'
    var p_intro2 = document.getElementById('p_intro2')
    p_intro2.style.color = 'white'
    var p_intro3 = document.getElementById('p_intro3')
    p_intro3.style.color = 'white'
    var p_edu = document.getElementById('p_edu')
    p_edu.style.color = 'white'
    var p_edu_1 = document.getElementById('p_edu_1')
    p_edu_1.style.color = 'white'
    var p_edu_2 = document.getElementById('p_edu_2')
    p_edu_2.style.color = 'white'
    var p_skill = document.getElementById('p_skill')
    p_skill.style.color = 'white'
    var idname1 = document.getElementById('idname1')
    idname1.style.color = 'white'
    var idname8 = document.getElementById('idname8')
    idname8.style.color = 'white'
    var idname2 = document.getElementById('idname2')
    idname2.style.color = 'white'
    var idname3 = document.getElementById('idname3')
    idname3.style.color = 'white'
    var idname4 = document.getElementById('idname4')
    idname4.style.color = 'white'
    var idname5 = document.getElementById('idname5')
    idname5.style.color = 'white'
    var idname6 = document.getElementById('idname6')
    idname6.style.color = 'white'
    var idname7 = document.getElementById('idname7')
    idname7.style.color = 'white'
    var project = document.getElementById('project')
    project.style.backgroundColor = 'black'
    var project_h1 = document.getElementById('project_h1')
    project_h1.style.color = 'white'
    var project_div = document.getElementById('project-div')
    project_div.style.color = 'white'
    var contact = document.getElementById('contact')
    contact.style.backgroundColor = 'black'
    contact.style.color = 'white'
    var name = document.getElementById('name')
    name.style.backgroundColor = '#1a1a1a'
    name.style.color = 'white'
    var message = document.getElementById('message')
    message.style.backgroundColor = '#1a1a1a'
    message.style.color = 'white'
    var email = document.getElementById('email')
    email.style.backgroundColor = '#1a1a1a'
    email.style.color = 'white'
    var phone = document.getElementById('phone')
    phone.style.backgroundColor = '#1a1a1a'
    phone.style.color = 'white'
    var send_msg = document.getElementById('send_msg')
    send_msg.style.backgroundColor = '#1a1a1a'
    send_msg.style.color = 'white'
}




const darkOff = () => {
    var on = document.getElementById('darkmode_on');
    var off = document.getElementById('darkmode_off');
    on.style.display = 'none';
    off.style.display = 'block';
    var home = document.getElementById('home')
    home.style.backgroundImage = 'radial-gradient(white, white)'

    var nav = document.getElementById('nav');
    nav.style.backgroundColor = 'white';
    var mob_nav = document.getElementById('mob-nav');
    mob_nav.style.backgroundColor = 'white';
    var nav_btn_logo = document.getElementById('nav-btn-logo');
    nav_btn_logo.style.backgroundColor = 'black'
    nav_btn_logo.style.color = 'white'
    var nav_link_soc_1 = document.getElementById('nav_link_soc_1');
    var nav_link_soc_2 = document.getElementById('nav_link_soc_2');
    var nav_link_soc_3 = document.getElementById('nav_link_soc_3');
    var nav_link_soc_4 = document.getElementById('nav_link_soc_4');
    nav_link_soc_1.style.color = 'black'
    nav_link_soc_2.style.color = 'black'
    nav_link_soc_3.style.color = 'black'
    nav_link_soc_4.style.color = 'black'
    var page_links_1 = document.getElementById('page_links_1')
    page_links_1.style.color = 'black'
    var page_links_2 = document.getElementById('page_links_2')
    page_links_2.style.color = 'black'
    var page_links_3 = document.getElementById('page_links_3')
    page_links_3.style.color = 'black'
    var page_links_4 = document.getElementById('page_links_4')
    page_links_4.style.color = 'black'
    var first_sec = document.getElementById('first_sec');
    first_sec.style.color = 'black'
    var mca = document.getElementById('mca')
    var intro = document.getElementById('intro')
    var tagline = document.getElementById('tagline')
    mca.style.color = '#1a1a1a'
    intro.style.color = '#1a1a1a'
    tagline.style.color = 'black'
    var about = document.getElementById('about')
    about.style.backgroundColor = 'white'
    var about_h1 = document.getElementById('about_h1')
    about_h1.style.color = 'black'
    var main_about_h1 = document.getElementById('main_about_h1')
    main_about_h1.style.color = 'black'
    var p = document.getElementById('p')
    p.style.color = 'black'
    var p_intro = document.getElementById('p_intro')
    p_intro.style.color = 'black'
    var p_intro2 = document.getElementById('p_intro2')
    p_intro2.style.color = 'black'
    var p_intro3 = document.getElementById('p_intro3')
    p_intro3.style.color = 'black'
    var p_edu = document.getElementById('p_edu')
    p_edu.style.color = 'black'
    var p_edu_1 = document.getElementById('p_edu_1')
    p_edu_1.style.color = 'black'
    var p_edu_2 = document.getElementById('p_edu_2')
    p_edu_2.style.color = 'black'
    var p_skill = document.getElementById('p_skill')
    p_skill.style.color = 'black'
    var idname1 = document.getElementById('idname1')
    idname1.style.color = 'black'
    var idname8 = document.getElementById('idname8')
    idname8.style.color = 'black'
    var idname2 = document.getElementById('idname2')
    idname2.style.color = 'black'
    var idname3 = document.getElementById('idname3')
    idname3.style.color = 'black'
    var idname4 = document.getElementById('idname4')
    idname4.style.color = 'black'
    var idname5 = document.getElementById('idname5')
    idname5.style.color = 'black'
    var idname6 = document.getElementById('idname6')
    idname6.style.color = 'black'
    var idname7 = document.getElementById('idname7')
    idname7.style.color = 'black'
    var project = document.getElementById('project')
    project.style.backgroundColor = 'white'
    var project_h1 = document.getElementById('project_h1')
    project_h1.style.color = 'black'
    var project_div = document.getElementById('project-div')
    project_div.style.color = 'black'
    var contact = document.getElementById('contact')
    contact.style.backgroundColor = 'white'
    contact.style.color = 'black'
    var name = document.getElementById('name')
    name.style.backgroundColor = '#e7e7e7'
    name.style.color = 'black'
    var message = document.getElementById('message')
    message.style.backgroundColor = '#e7e7e7'
    message.style.color = 'black'
    var email = document.getElementById('email')
    email.style.backgroundColor = '#e7e7e7'
    email.style.color = 'black'
    var phone = document.getElementById('phone')
    phone.style.backgroundColor = '#e7e7e7'
    phone.style.color = 'black'
    var send_msg = document.getElementById('send_msg')
    send_msg.style.backgroundColor = '#1a1a1a'
    send_msg.style.color = 'white'

}

export { darkOff, darkOn }